# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np
import pprint

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.21.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512C

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
arr = np.array([0 for i in range(10)])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
a = np.array([[1 for i in range(10)]for j in range(10)]) #10x10 array
print(f"Memory size : {a.size*a.itemsize} Bytes")

Memory size : 400 Bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [32]:
#python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
arr = np.array([0 for i in range(10)])
arr[4] = 1
arr 

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
arr = np.array([i for i in range(10,50)])
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
arr = np.array([i for i in range(11)])
revarr = []
k = 10
for j in range(11):
    revarr.append(arr[k])
    k = k-1

revarr
    


[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
mat = np.array([[0 for i in range(3)]for j in range(3)])
k = 0
for i in range(3):
    for j in range(3):
        mat[i][j] = int(k)
        k = k+1
        
mat

#I know about reshape also 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
non = np.nonzero([1,2,0,0,4,0])
non

# or

# a = [1,2,0,0,4,0]
# non = []
# for i in range(len(a)):
#     if a[i] != 0:
#         non.append(i)

# non






(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
iden = np.array([[1 for i in range(3)]for j in range(3)])
iden

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
ran = np.array([[[np.random.random() for i in range(3)]for j in range(3)]for k in range(3)])
pprint.pprint(ran)

array([[[0.38841892, 0.7479131 , 0.9635775 ],
        [0.43662683, 0.95055364, 0.94099774],
        [0.93718803, 0.91749122, 0.70279886]],

       [[0.15149722, 0.39042227, 0.20657002],
        [0.90047236, 0.95331877, 0.54104028],
        [0.16136765, 0.5621458 , 0.43911328]],

       [[0.66302418, 0.15635726, 0.50607305],
        [0.21974641, 0.99223269, 0.68316287],
        [0.85565972, 0.36118751, 0.92687754]]])


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
arr = np.array([[np.random.random() for i in range(10)]for j in range(10)])
print(arr)
print("Min : ",arr.min())
print("Max : ",arr.max())

[[0.86257899 0.10964556 0.74036022 0.32051221 0.78342687 0.01389204
  0.84465411 0.39198246 0.40899981 0.56244682]
 [0.61353398 0.63866525 0.04098821 0.70767645 0.02872386 0.39534201
  0.03427659 0.52887027 0.91400238 0.68191974]
 [0.43767935 0.37335107 0.88353677 0.74127069 0.41252754 0.65519112
  0.40202989 0.0533005  0.96005678 0.39364299]
 [0.56647212 0.14266231 0.78158004 0.46208417 0.89696747 0.53848729
  0.04345392 0.9272129  0.2094092  0.98767133]
 [0.61747185 0.03162674 0.05898578 0.71323215 0.05678576 0.4538249
  0.86985629 0.49351424 0.50062728 0.2672439 ]
 [0.81663689 0.86322741 0.55027704 0.60382636 0.00802846 0.83967896
  0.21166085 0.41947622 0.01754752 0.4860527 ]
 [0.41841793 0.85033667 0.90283854 0.16095868 0.45672626 0.57967677
  0.83834328 0.58295493 0.16849613 0.18115044]
 [0.40864117 0.42691298 0.94491986 0.02449836 0.31264816 0.28597131
  0.70268555 0.80413487 0.66897343 0.00849317]
 [0.28582277 0.74540094 0.65555755 0.4285848  0.94405412 0.99566942
  0.65622122 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
vector = np.random.random(30)
print(vector)
print("Mean : ",vector.mean())

[0.52966931 0.79368628 0.63834168 0.56848283 0.85768879 0.84865161
 0.0480259  0.98690605 0.90673456 0.17668807 0.62354836 0.41785505
 0.02792564 0.92465626 0.09456263 0.67251897 0.21052968 0.09181879
 0.53206796 0.09285741 0.34001856 0.21231112 0.08497234 0.56791948
 0.11374753 0.57304351 0.78809403 0.65469092 0.81471466 0.69102932]
Mean :  0.4961252437825292


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
arr = np.array([[0 for i in range(5)]for j in range(5)])
for i in range(5):
    for j in range(5):
        if i==0 or i==4:
            arr[i][j] = 1
        else:
            if j==0 or j==4:
                arr[i][j] = 1

arr

            

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [30]:
arr = np.array([[1 for i in range(5)]for j in range(5)])
arrpad = np.pad(Z, pad_width=0, mode='constant', constant_values=0)
print(arrpad)



[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [38]:
#nan
#false
#false
#nan
#true
#false



#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [40]:
arr = np.array([[0 for i in range(5)]for j in range(5)])
k=1
for row in range(5):
    for col in range(5):
        if row==col+1:
            arr[row][col] = k
            k = k + 1

arr


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [47]:
arr = np.array([[0 for i in range(8)]for j in range(8)])
arr[1::2][::2] = 1      #[1::2] for every odd index and [::2] for every even index
arr[::2][1::2] = 1
print(arr)

[[0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [63]:
arr = np.array([[[1 for i in range(8)]for j in range(7)]for k in range(6)])
print(arr.shape)
k = 0
for i in range(6):
    for j in range(7):
        for l in range(8):
            k = k+1
            if k == 100:
                print((i,j,l))       



(6, 7, 8)
(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [72]:
#tile function just copies the array and merge it with the original array. np.tile(array,repetitions)
arr = np.array([[0,1],[1,0],[0,1],[1,0],[0,1],[1,0],[0,1],[1,0]])
arrr = np.tile(arr,4)
arrr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [78]:
# #Normalising is X - mean of X/ standard dev of X. Where X is a list of elements
arr = np.array([[np.random.random() for i in range(5)]for j in range(5)])
print(arr)
normarr = (arr - np.mean(arr))/(np.std(arr))
print(normarr)



[[0.35174762 0.01915196 0.29683788 0.29729262 0.4764674 ]
 [0.46842333 0.46907649 0.37039418 0.39730273 0.21150076]
 [0.1632986  0.69041706 0.38570542 0.62194025 0.42193529]
 [0.67808584 0.59436837 0.78133246 0.70022315 0.77329778]
 [0.22830583 0.159694   0.92389814 0.32620377 0.87482275]]
[[-0.49167824 -1.90726149 -0.72538335 -0.72344789  0.03915019]
 [ 0.00491323  0.00769322 -0.41231533 -0.29778802 -1.08859253]
 [-1.29374905  0.949756   -0.34714814  0.65830713 -0.19294769]
 [ 0.89727224  0.54095657  1.33670727  0.99149235  1.30251031]
 [-1.01706734 -1.30909086  1.94349085 -0.60039716  1.73461771]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [81]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
type(color)

numpy.dtype[void]

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [90]:
mat1 = np.array([[1 for i in range(3)]for j in range(5)])
print(mat1)
mat2 = np.array([[1 for i in range(2)]for j in range(3)])
print(mat2)
multi = np.dot(mat1,mat2)
print(multi)


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1]
 [1 1]
 [1 1]]
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [96]:
arr = np.array([1 for i in range(10)])
print(arr)
for i in range(len(arr)):
    if i >= 3 and i < 7:
        arr[i] = -1*arr[i]

print(arr)
    


[1 1 1 1 1 1 1 1 1 1]
[ 1  1  1 -1 -1 -1 -1  1  1  1]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [111]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [121]:
Z = np.array([1 for i in range(4)])
print(Z)
print(Z**Z)     #Legal
print(2 << Z >> 2) #legal
print(Z<-Z)         #Illegal
print(1j*Z)         #Legal
print(Z/1/1)        #Legal
# print(Z<Z>Z)  #Illegal

[1 1 1 1]
[1 1 1 1]
[1 1 1 1]
[False False False False]
[0.+1.j 0.+1.j 0.+1.j 0.+1.j]
[1. 1. 1. 1.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [128]:
#0/0 Not a number - nan
#0
np.array([np.nan]).astype(int).astype(float) #Astype cast a datatype into other. nan casted to integer. that furthur got casted into float

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [132]:
arr = np.random.uniform(-5,+5,10)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[-1. -2.  4.  5.  4. -2. -3.  2. -4. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [139]:
arr1 = np.random.randint(1,10,10)
arr2 = np.random.randint(1,10,10)
common = np.intersect1d(arr1,arr2)
print(common)

[1 4 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [145]:
# Suicide mode on
defaults = np.seterr(all="ignore")      #setarr is used to ignore the numpy warnings
arr = np.array([1]) / 0
arr



array([inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [148]:
#Nope. 


1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [155]:
print(f"Yesterday : {np.datetime64('today') - 1}")
print(f"Today : {np.datetime64('today')}")
print(f"Tomorrow : {np.datetime64('today') +1 }")

Yesterday : 2021-09-08
Today : 2021-09-09
Tomorrow : 2021-09-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [165]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [182]:
A = np.array([1.0 for i in range(3)])
B = np.array([1.0 for i in range(3)])
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)




array([-1., -1., -1.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [189]:
arr = np.random.uniform(0,10,10)
print(np.floor(arr))
print(arr - arr%1)
print(arr // 1)
print(arr.astype(int))

[8. 7. 8. 2. 4. 5. 9. 0. 9. 3.]
[8. 7. 8. 2. 4. 5. 9. 0. 9. 3.]
[8. 7. 8. 2. 4. 5. 9. 0. 9. 3.]
[8 7 8 2 4 5 9 0 9 3]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [193]:
mat = np.array([[i for i in range(5)]for j in range(5)])
mat

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [197]:
def generate():
    arr = []
    for i in range(10):
        arr.append(i)
    return arr

arr = generate()
print(arr)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [211]:
vec = np.linspace(0,1,12)[1:11]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [222]:
vec = np.random.randint(1,10,10)
vec.sort()
vec

array([2, 5, 5, 6, 7, 8, 9, 9, 9, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [233]:
arr = np.array([i for i in range(10)])
arr
np.add.reduce(arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [236]:
A = np.random.randint(1,10,10)
B = np.random.randint(1,10,10)
print(A==B)

[ True False False False False False False False False False]


#### 43. Make an array immutable (read-only) (★★☆)

In [245]:
arr = np.array([i for i in range(10)])
print(arr)
arr[4] = 100
print(arr)
arr.flags.writeable = False
# arr[4] = 200              This give read only error now

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3 100   5   6   7   8   9]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [251]:
arr = np.array([[np.random.random() for i in range(2)]for j in range(10)])
X,Y = arr[:,0], arr[:,1]            #X = 0th colomn of the arr array and Y = 1th colomn of the arr array
Z = np.sqrt(X**2+Y**2)
A = np.arctan2(Y,X)
print(Z)
print(A)



[0.91194946 0.96060574 1.0150074  0.42472456 0.74110539 1.07525702
 0.73936502 0.98616919 1.01211058 0.81749899]
[0.92842879 0.30472152 0.38321181 0.42620723 1.34125574 0.8417142
 0.05079268 0.2415731  0.16406027 1.5465653 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [259]:
vec = np.array(np.random.randint(1,11,10))
print(vec)
print(f"Max : {np.max(vec)}")

vec[vec.argmax()] = 0           #argmax return the indice of the max element
print(vec)


[ 8  2  2  3  6  8 10  8 10  7]
Max : 10
[ 8  2  2  3  6  8  0  8 10  7]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [264]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))             #Copied didnt knew the systax. Learnt now
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [277]:
X = np.array([np.random.random() for i in range(10)])
print(X)
Y = np.array([np.random.random() for i in range(10,20)])
print(Y)
C = np.array([[1.0 for i in range(10)]for j in range(10)])
print(C)
for i in range(10):
    for j in range(10):
        C[i][j] = 1/(X[i] - Y[j])

print(C)

[0.79857758 0.81725877 0.94916129 0.04947498 0.88563095 0.20424365
 0.59903161 0.33464357 0.48105161 0.62161878]
[0.00199527 0.02051206 0.32625418 0.0645511  0.30044533 0.27431594
 0.58890831 0.30235966 0.30456888 0.28407872]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[  1.25536305   1.2852388    2.11719344   1.36234866   2.007499
    1.90744452   4.76941618   2.01524363   2.02425583   1.94363889]
 [  1.2265973    1.25510402   2.03664086   1.32853701   1.93493419
    1.84181454   4.37923364   1.94212805   1.95049681   1.87553903]
 [  1.05578112   1.07683285   1.60537581   1.13044141   1.5415067
    1.48182098   2.77582716   1.54606908   1.55136793   1.5035727 ]
 [ 21.06163134  34.52690668  -3.61298815 

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [278]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [282]:
arr = np.array([[1 for i in range(5)]for j in range(5)])
print(arr)
for i in range(5):
    for j in range(5):
        print(arr[i][j])

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [290]:
arr = np.random.randint(0,10,100)
print(arr)
scaler = np.random.uniform(0,100)
print(scaler)
index = (np.abs(arr-scaler)).argmin()
print(arr[index])

[1 1 7 2 2 7 3 4 3 7 8 6 3 9 9 0 1 0 6 6 4 2 2 1 1 8 1 2 4 6 5 4 2 5 4 2 1
 6 5 0 6 4 0 6 7 9 3 9 0 0 2 9 9 1 1 2 9 7 2 5 3 9 9 9 1 9 6 5 3 5 9 4 3 0
 2 4 3 5 5 1 0 2 6 1 2 0 7 7 6 8 9 4 8 7 9 8 9 4 0 8]
65.78625487690107
9


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [296]:
arr = np.zeros(10,[('position',[('x', float, 1),('y', float, 1)]),('color',[('r', float, 1),('g', float, 1),('b', float, 1)])])
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-296-aec57ba3dd36>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  arr = np.zeros(10, [('position',[('x', float, 1),('y', float, 1)]),('color',[('r', float, 1),('g', float, 1),('b', float, 1)])])


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [319]:
arr = np.random.random((100,2))
print(arr)
X,Y = np.atleast_2d(arr[:,0], arr[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)




# Z = np.random.random((100,2))
# X,Y = np.atleast_2d(Z[:,0], Z[:,1])
# D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
# print(D)


[[0.5628117  0.40307668]
 [0.15910467 0.80405241]
 [0.06521555 0.74678281]
 [0.06080445 0.27699485]
 [0.44096108 0.18816863]
 [0.92361524 0.49248076]
 [0.56902696 0.1106676 ]
 [0.00193973 0.91870202]
 [0.9787227  0.16748342]
 [0.20589346 0.62669642]
 [0.36795035 0.76084549]
 [0.58881097 0.96822799]
 [0.51673021 0.37430863]
 [0.29187216 0.46781008]
 [0.78581281 0.71940878]
 [0.10904338 0.95773304]
 [0.53751632 0.6796523 ]
 [0.8445325  0.07450367]
 [0.76817375 0.79293111]
 [0.32441141 0.61745136]
 [0.2324263  0.07677492]
 [0.38142413 0.87186526]
 [0.88662583 0.28282514]
 [0.89787838 0.74054231]
 [0.78800689 0.03114274]
 [0.91866038 0.03404384]
 [0.06274953 0.90871197]
 [0.28682567 0.02206831]
 [0.08321617 0.1643462 ]
 [0.1360385  0.61192211]
 [0.97026159 0.06885927]
 [0.55256961 0.72717584]
 [0.86102581 0.08954684]
 [0.78974271 0.62973289]
 [0.43761603 0.17230219]
 [0.27960494 0.05720105]
 [0.22254027 0.91322189]
 [0.15056575 0.7161271 ]
 [0.88662166 0.60017247]
 [0.54635206 0.30050614]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [337]:
floatarr = np.random.random(10)*100
print(floatarr)
intarr = []
for i in range(len(floatarr)):
    intarr.append(int(floatarr[i]))

print(intarr)


[83.76552549 85.80847339 87.14327994 78.49704137 99.9096739  98.32561943
 16.64897058 83.78124791 93.50373566 31.2316546 ]
[83, 85, 87, 78, 99, 98, 16, 83, 93, 31]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [353]:
from io import StringIO

stri = StringIO('''1, 2, 3, 4, 5

                   6,  ,  , 7, 8

                    ,  , 9,10, 11''')
arr = np.genfromtxt(stri, delimiter=",", dtype=np.int)
print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-353-4d992b0e0037>:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(stri, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [361]:
arr = np.array([[1 for i in range(3)]for j in range(3)])        #3x3 matrix (shape = (3,3))
for index in np.ndindex((3,3)):
    print(index, arr[index])

(0, 0) 1
(0, 1) 1
(0, 2) 1
(1, 0) 1
(1, 1) 1
(1, 2) 1
(2, 0) 1
(2, 1) 1
(2, 2) 1


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [370]:

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0                                                
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)



[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)"

In [399]:
arr = np.array([[0 for i in range(5)]for j in range(5)])
p = 3

np.put(arr, np.random.choice(25, p),1)
print(arr)



[[0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [417]:
mat = np.array([[np.random.random()*100 for i in range(5)]for j in range(5)])
print(mat)
for i in range(5):
    mat[i] = mat[i] - mat[i].mean()             #mat[i] is a particular row

print(mat)

[[63.80179435 78.86503186 80.25284622  5.09634172 94.56408158]
 [ 3.49792236 62.27821056 81.85552017 18.56493212 12.04992487]
 [51.87654794 35.32420908 14.26439242 30.43088152 87.42497642]
 [ 3.02408216  4.2310447  20.47475373 76.3531247  40.94816291]
 [59.27405846 36.53538971 23.00253642  6.58262335 78.68782425]]
[[ -0.7142248   14.34901272  15.73682708 -59.41967743  30.04806243]
 [-32.15137966  26.62890855  46.20621815 -17.08436989 -23.59937715]
 [  8.01234647  -8.5399924  -29.59980906 -13.43331996  43.56077495]
 [-25.98215148 -24.77518894  -8.53147991  47.34689106  11.94192927]
 [ 18.45757202  -4.28109673 -17.81395002 -34.23386309  37.87133781]]


#### 59. How to sort an array by the nth column? (★★☆)

In [429]:
arr = np.array([[np.random.randint(10) for i in range(5)]for j in range(5)])
print(arr)
n = 2
arr[:,n].sort()
print(arr)



[[3 1 4 3 1]
 [3 8 9 5 2]
 [0 9 3 5 9]
 [6 9 3 2 7]
 [8 6 0 9 7]]
[[3 1 0 3 1]
 [3 8 3 5 2]
 [0 9 3 5 9]
 [6 9 4 2 7]
 [8 6 9 9 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [461]:
arr = np.array([[np.random.randint(2) for i in range(3)]for j in range(3)])
print(arr)
for i in range(3):
    if arr[:,i].any() == 0:     #Check every colomn for null-ness
        print("Present")
    else:
        print("Absent")

[[0 1 1]
 [0 1 0]
 [0 0 1]]
Present
Absent
Absent


#### 61. Find the nearest value from a given value in an array (★★☆)

In [5]:
arr = np.random.randint(0,10,10)
val = 0.3
nearest = arr.flat[np.abs(arr - val).argmin()]      #Flat function is used to iterate in a 1D array
print(nearest)

2


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [32]:
arr1 = np.array([[i for i in range(3)]for j in range(1)])
print(arr1.shape)
arr2 = np.array([[i for i in range(1)]for j in range(3)])
print(arr2.shape)
iter = np.nditer([arr1,arr2,None])

for i,j,k in iter: 
    k[...] = i + j

print(iter.operands[2])



(1, 3)
(3, 1)
[[0 1 2]
 [0 1 2]
 [0 1 2]]


#### 63. Create an array class that has a name attribute (★★☆)

In [36]:
#Copies but learnt too
class array(np.ndarray):
    def __new__(arr, array, name):
        obj = np.asarray(array).view(arr)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

out = array(np.arange(10), "range_10")
print (out.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [45]:
arr1 = np.array([1 for i in range(10)])
print(arr1)
arr2 = np.random.randint(0,len(arr1),20)
print(arr2)
bin  =  np.bincount(arr2, weights=None, minlength=len(arr1))
arr1 = arr1 + bin
print(arr1)


[1 1 1 1 1 1 1 1 1 1]
[6 4 7 8 5 7 6 1 8 8 3 0 8 9 6 2 5 9 2 3]
[2 2 3 3 2 3 4 3 5 3]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [52]:
X = np.array([i for i in range(10)])
I = np.array([(i+1) for i in range(len(X))])
F = np.bincount(I,X)
print(F)



[0. 0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [59]:
w, h = 256, 256
arr = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(arr.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [78]:
arr = np.array([[[[np.random.randint(1,10) for i in range(4)]for j in range(4)]for k in range(4)]for l in range(4)])
arr.shape
sum = arr.sum(axis=(-4,-3))
print(sum)



[[ 60 102  81  77]
 [ 78  85  79  75]
 [ 96  81  76  57]
 [ 65  73  90  83]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [84]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sum = np.bincount(S, weights=D)
D_count = np.bincount(S)
D_mean = D_sum / D_count
print(D_mean)

[0.47560816 0.49037949 0.57026411 0.49248639 0.47948801 0.32132247
 0.35071145 0.66186833 0.56842453 0.51043002]


#### 69. How to get the diagonal of a dot product? (★★★)

In [89]:
arr1 = np.array([[i for i in range(4)]for j in range(4)])
print(arr1)
arr2 = np.array([[(i+1) for i in range(4)]for j in range(4)])
print(arr2)
dot = np.dot(arr1,arr2)
print(dot)
diag = np.diag(dot)
print(diag)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[ 6 12 18 24]
 [ 6 12 18 24]
 [ 6 12 18 24]
 [ 6 12 18 24]]
[ 6 12 18 24]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [91]:
vec = np.array([1,2,3,4,5])
newvec = []
k = 0
for i in range(17):
    if i%4 == 0:
        newvec.append(vec[k])
        k = k+1
    else:
        newvec.append(0)

newvec


[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [104]:
arr1 = np.array([[[1 for i in range(3)]for j in range(5)]for k in range(5)])
arr2 = np.array([[2 for i in range(5)]for j in range(5)])
print(arr1.shape)
print(arr2.shape)
print(arr1*arr2[:,:,None])          #3D *2D is not possible hence we have to add another None dimention in the 2D array

(5, 5, 3)
(5, 5)
[[[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]
  [2 2 2]]]


#### 72. How to swap two rows of an array? (★★★)

In [122]:
# A = np.arange(25).reshape(5,5)
# print(A)
# A[[0,1]] = A[[1,0]]
# print(A)

arr = np.array([[np.random.randint(0,10) for i in range(5)]for j in range(5)])
print(arr)
arr[[0,1]] = arr[[1,0]]
arr

[[6 2 5 2 2]
 [2 8 3 9 0]
 [7 5 9 7 5]
 [3 9 1 2 8]
 [8 8 4 6 3]]


array([[2, 8, 3, 9, 0],
       [6, 2, 5, 2, 2],
       [7, 5, 9, 7, 5],
       [3, 9, 1, 2, 8],
       [8, 8, 4, 6, 3]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [124]:
#copied but learn
face = np.random.randint(0,100,(10,3))
F = np.roll(face.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1,  6) ( 1, 26) ( 1, 59) ( 1, 99) ( 2, 22) ( 2, 40) ( 2, 65) ( 2, 70)
 ( 6, 29) ( 6, 34) ( 6, 67) ( 6, 70) ( 6, 99) (22, 65) (23, 23) (23, 35)
 (26, 28) (26, 59) (26, 95) (28, 95) (29, 34) (40, 70) (40, 94) (40, 99)
 (67, 70) (73, 74) (73, 80) (74, 80) (94, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [136]:
C = np.bincount([1,2,3,4,5,6,7])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 2 3 4 5 6 7]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [141]:
def average(a, n) :
    ret = np.cumsum(a)              #cumsum = cummulative sum of an array
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
arr = np.array([i for i in range(10)])
print(average(arr, 3))

[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [164]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [172]:
arr = np.random.uniform(1.0,100.0,10)
print(arr)
narr = np.negative(arr)
print(narr)

[30.88483411 92.58219658 32.59378908 35.70604814 96.23421682 86.76801538
 87.40181723 46.19271409 41.14077732 88.78351265]
[-30.88483411 -92.58219658 -32.59378908 -35.70604814 -96.23421682
 -86.76801538 -87.40181723 -46.19271409 -41.14077732 -88.78351265]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [173]:
#Copied and learmt
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.97736753 17.16963585  8.09019956 15.54872465  2.49890576  3.68324235
  6.88432328  7.3102323   4.18944213  1.85627663]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [174]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
    
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 8.40944441  2.09290837  2.17573761  1.28200723  6.05268551  1.94911518
   8.21045874  0.86482492  0.05077189  2.3593724 ]
 [ 1.75940512  4.05757457  1.71955131  5.58930458  7.60557689 14.34630822
   8.28783886  5.78105429  1.93169498 10.37186553]
 [ 5.62313465 14.13629076 10.45159523  6.67573621  8.39952688  5.84961944
   0.62206732 13.16644156  9.70914479 12.33753021]
 [ 1.01161777  9.38458968  8.50732464  4.94766611  0.14846207  1.01071604
   6.65476935  6.53320073  6.79448751  3.93650795]
 [11.60853554  5.07843315  8.95483037 12.64898618  1.29536654 11.17200882
   4.33556094  4.06780056  9.9078058   1.10883403]
 [ 0.63703496  6.91467551  2.89795396  0.86504638  5.31591957  8.59457394
   2.76403486  6.90510974  2.16000809  8.6295373 ]
 [ 2.41788278  8.0600145   1.61565803  2.31966351 11.14854755 15.26303291
   9.54431231  9.95834594  1.67484206 14.10396823]
 [ 9.80472859  3.65559942  8.1526706  11.89646271  0.79030122 12.59621853
   5.88305093  2.26428076  8.88583633  3.1910451 ]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [175]:
#Tough but copied and understood the logic
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 1 6 1 5 0 1 9 9 7]
 [9 2 8 8 0 2 9 8 9 1]
 [1 4 3 6 5 1 9 7 7 4]
 [1 5 2 7 7 4 2 0 7 2]
 [8 9 5 5 0 3 4 6 3 9]
 [4 5 6 4 2 1 4 3 5 7]
 [0 8 1 8 2 9 3 5 2 9]
 [0 1 8 0 0 4 5 4 2 3]
 [1 7 9 1 7 0 3 8 7 6]
 [0 9 0 2 2 8 9 1 9 1]]
[[0 0 0 0 0]
 [0 8 1 6 1]
 [0 9 2 8 8]
 [0 1 4 3 6]
 [0 1 5 2 7]]


<ipython-input-175-5269487c2f79>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [207]:
Z = np.array([i for i in range(1,15)])
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)




[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [213]:
mat = np.array([[np.random.randint(0,10)for i in range(5)]for j in range(5)])
print(mat)
print(mat.shape)
rank =  np.linalg.matrix_rank(mat) 
print(rank)

[[8 2 8 7 8]
 [2 4 0 6 1]
 [3 1 4 1 1]
 [6 8 3 3 5]
 [0 8 8 1 5]]
(5, 5)
5


#### 83. How to find the most frequent value in an array?

In [215]:
arr = np.random.randint(1,5,50)
print(arr)
freq = np.bincount(arr).argmax()
print(freq)

[4 2 1 4 4 1 1 2 3 4 2 1 1 2 3 3 3 3 4 4 3 3 4 3 2 3 3 4 1 4 2 3 3 3 3 3 3
 1 3 1 3 2 1 1 2 4 4 1 2 3]
3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [228]:
mat = np.array([[np.random.randint(5)for x in range(10)]for y in range(10)])
n = 3
i = 1 + (mat.shape[0]-3)
j = 1 + (mat.shape[1]-3)
C = stride_tricks.as_strided(mat, shape=(i, j, n, n), strides=mat.strides + mat.strides)
print(C)


[[[[4 0 1]
   [2 0 3]
   [4 4 3]]

  [[0 1 0]
   [0 3 1]
   [4 3 1]]

  [[1 0 2]
   [3 1 3]
   [3 1 1]]

  [[0 2 3]
   [1 3 0]
   [1 1 0]]

  [[2 3 3]
   [3 0 3]
   [1 0 2]]

  [[3 3 4]
   [0 3 0]
   [0 2 1]]

  [[3 4 1]
   [3 0 1]
   [2 1 4]]

  [[4 1 4]
   [0 1 4]
   [1 4 1]]]


 [[[2 0 3]
   [4 4 3]
   [1 1 0]]

  [[0 3 1]
   [4 3 1]
   [1 0 2]]

  [[3 1 3]
   [3 1 1]
   [0 2 0]]

  [[1 3 0]
   [1 1 0]
   [2 0 3]]

  [[3 0 3]
   [1 0 2]
   [0 3 4]]

  [[0 3 0]
   [0 2 1]
   [3 4 0]]

  [[3 0 1]
   [2 1 4]
   [4 0 3]]

  [[0 1 4]
   [1 4 1]
   [0 3 1]]]


 [[[4 4 3]
   [1 1 0]
   [1 1 3]]

  [[4 3 1]
   [1 0 2]
   [1 3 1]]

  [[3 1 1]
   [0 2 0]
   [3 1 4]]

  [[1 1 0]
   [2 0 3]
   [1 4 3]]

  [[1 0 2]
   [0 3 4]
   [4 3 0]]

  [[0 2 1]
   [3 4 0]
   [3 0 4]]

  [[2 1 4]
   [4 0 3]
   [0 4 1]]

  [[1 4 1]
   [0 3 1]
   [4 1 1]]]


 [[[1 1 0]
   [1 1 3]
   [4 4 3]]

  [[1 0 2]
   [1 3 1]
   [4 3 3]]

  [[0 2 0]
   [3 1 4]
   [3 3 0]]

  [[2 0 3]
   [1 4 3]
   [3 0 3]]

  [[0 3 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [241]:
arr = np.array([[0 for i in range(5)]for j in range(5)])
print(arr)
for i in range(5):
    for j in range(5):
        if (i==j):
            arr[i][j] = np.random.randint(1,5)      #Diagonal
        else:
            temp = np.random.randint(10)        #offdiagonal
            arr[i][j] = temp
            arr[j][i] = temp

print(arr)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[2 4 5 8 6]
 [4 3 8 3 9]
 [5 8 4 0 6]
 [8 3 0 4 7]
 [6 9 6 7 3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [253]:
p = 5
n = 10
mat = np.array([[[1 for i in range(n)]for j in range(n)]for k in range(p)])

vec = np.array([[[1 for i in range(1)]for j in range(n)]for k in range(p)])
tsum = np.tensordot(mat, vec, axes=[[0, 2], [0, 1]])
print(tsum)

[[50]
 [50]
 [50]
 [50]
 [50]
 [50]
 [50]
 [50]
 [50]
 [50]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [256]:
arr = np.array([[1 for i in range(16)]for j in range(16)])
blocksum = np.add.reduceat(np.add.reduceat(arr, np.arange(0, arr.shape[0], 4), axis=0),np.arange(0, arr.shape[1], 4), axis=1)
print(blocksum)

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [258]:
#Could not understand

#### 89. How to get the n largest values of an array (★★★)

In [275]:
mat = np.array([np.random.randint(1,10) for i in range(15)])
print(mat)
mat.sort()
print(mat)
n = 4
reversemat = []
for i in range(len(mat)-1,-1,-1):
    reversemat.append(mat[i])
print(reversemat)
for i in range(n):
    print(reversemat[i])
    

[1 7 6 5 7 7 3 6 5 9 7 7 3 8 8]
[1 3 3 5 5 6 6 7 7 7 7 7 8 8 9]
[9, 8, 8, 7, 7, 7, 7, 7, 6, 6, 5, 5, 3, 3, 1]
9
8
8
7


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [297]:
#This will work for 3 arrays. For more arrays i have to edit the function. Cant figure out how to do it for arbitrary arrays

def cartprod(arrays):
    array = []
    for i in arrays:
        array.append(i)
    # print(array)
    # print(len(array))
    for i in range(len(array[0])):
        for j in range(len(array[1])):
            for k in range(len(array[2])):
                tupl = (array[0][i],array[1][j],array[2][k])
                print(tupl)
        
    
    
    
ar1 = [1,2,3,4,5]
ar2 = [6,7,8,9]
ar3 = [10,11,12]
cartprod((ar1,ar2,ar3))



(1, 6, 10)
(1, 6, 11)
(1, 6, 12)
(1, 7, 10)
(1, 7, 11)
(1, 7, 12)
(1, 8, 10)
(1, 8, 11)
(1, 8, 12)
(1, 9, 10)
(1, 9, 11)
(1, 9, 12)
(2, 6, 10)
(2, 6, 11)
(2, 6, 12)
(2, 7, 10)
(2, 7, 11)
(2, 7, 12)
(2, 8, 10)
(2, 8, 11)
(2, 8, 12)
(2, 9, 10)
(2, 9, 11)
(2, 9, 12)
(3, 6, 10)
(3, 6, 11)
(3, 6, 12)
(3, 7, 10)
(3, 7, 11)
(3, 7, 12)
(3, 8, 10)
(3, 8, 11)
(3, 8, 12)
(3, 9, 10)
(3, 9, 11)
(3, 9, 12)
(4, 6, 10)
(4, 6, 11)
(4, 6, 12)
(4, 7, 10)
(4, 7, 11)
(4, 7, 12)
(4, 8, 10)
(4, 8, 11)
(4, 8, 12)
(4, 9, 10)
(4, 9, 11)
(4, 9, 12)
(5, 6, 10)
(5, 6, 11)
(5, 6, 12)
(5, 7, 10)
(5, 7, 11)
(5, 7, 12)
(5, 8, 10)
(5, 8, 11)
(5, 8, 12)
(5, 9, 10)
(5, 9, 11)
(5, 9, 12)


#### 91. How to create a record array from a regular array? (★★★)

In [301]:
#Record arrays aka structured array
arr = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
recarr = np.core.records.fromarrays(arr.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(recarr)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [310]:
Z = np.array([np.random.randint(10)for i in range(1000)])       #Large vector 
print(f"Method 1 : {Z**3}")
print(f"Method 2 : {np.power(Z,3)}")
print(f"Method 3 : {np.einsum('i,i,i->i',Z,Z,Z)}")


Method 1 : [512   1 216   0 216 125   0 729   0 216 125  27   0 729  27   8   8  27
   8 729 343 125   0 343 216 343 216   8 125  64   0  64 343 343   1 729
 343   0   8 512  64 125  27  64 343 125 729 125 512 343   1 512  27 729
 125   8 343   1  64   1   0 512   1  64   8 512 125   1 512   0   8  64
 729 343  27 125   1 729  27  27   8  27 343 512   8 343 512 729 512 125
  64   8 512   1  64 729   0   8   1   1 216   0 512 729  64   1   8 512
  64 343  64 729   1   1   1 216  64 216 512  64   8 216 216  27 125 216
  27   0 125   1 125 343 216 343 729 216 216 216 125  64 729 512 125 512
 512 729   0  64   8   8 729  64 216  64   1  64   8   8   8   0   0   8
   0   0   0 125 216 216 343 512 512 512 216   0   0 343 512 343   8   0
 216 729 343 512   8 512   1 729   8 512  64   0  64   0 729 125  64  64
 729 729 512   8 512  64   8 512 512   1  27   0 125   8   0 125 216 512
 216  64   8   1   8 343   0 512 125   0   8  27 125 729 216 729   0 729
   1 216 729 216 216   1   1 343 343   0

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [313]:
#COpied and understood
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [329]:
arr = np.random.randint(0,2,(10,3))
print(arr)
unequal = []
for i in range(len(arr)):
    if arr[i][0] != arr[i][1] or arr[i][1] != arr[i][2]:
        unequal.append(arr[i])

print(unequal)

    

[[0 1 0]
 [0 0 0]
 [1 1 1]
 [0 1 1]
 [0 1 0]
 [1 1 1]
 [0 0 1]
 [0 0 0]
 [1 1 1]
 [1 0 1]]
[array([0, 1, 0]), array([0, 1, 1]), array([0, 1, 0]), array([0, 0, 1]), array([1, 0, 1])]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [344]:
def strtoint(stri):
    temparr = []
    for i in stri:
        temparr.append(int(i))
    return temparr

vec = np.array([np.random.randint(15) for i in range(15)])
print(vec)
pad = 10
binarr = []
for i in range(len(vec)):
    tempstr = np.binary_repr(vec[i]).zfill(pad)
    binarr.append(strtoint(tempstr))
    
pprint.pprint(binarr)

    

[ 9  4  0  8  6  2 13  5 14 10  2 13  1  5 13]
[[0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [354]:
arr = np.random.randint(0,2,(5,5))
uniquerows = np.unique(arr, axis=0)
print(uniquerows)

[[0 0 0 1 1]
 [0 1 0 0 0]
 [0 1 1 0 0]
 [1 0 1 0 0]
 [1 0 1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [367]:
arr1 = np.array([i for i in range(10)])
arr2 = np.array([i for i in range(10)])
print(np.einsum('i,i', arr1, arr2))    #inner
print(np.einsum('i,j->ij', arr1, arr2))    # outer
print(np.einsum('i->', arr1))       #Sum
print(np.einsum('i,i->i', arr1, arr2)) #mul


285
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]
45
[ 0  1  4  9 16 25 36 49 64 81]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [375]:
#I have no idea about this


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [388]:
#copied and understood
n = 4
X = np.array([[np.random.randint(10) for i in range(4)]for j in range(3)])
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


[]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [387]:
#copied and understood
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.15548488  0.24014158]
